accesstypes/accesstypes.go, accesstypes/domain.go, accesstypes/permission.go, accesstypes/resource.go, accesstypes/role.go, accesstypes/user.go
feature: Moved Enforcer interface to accesstypes (#47)
feature: Added new types for resolving permissions (#47)
=> feature: Moved Enforcer interface to accesstypes

resourceset/config.go, resourceset/config_registerall.go, resourceset/fieldmapper.go, resourceset/resourceset.go
refactor!: Change ResourceSet.Fields() to ResourceSet.FieldPermissions()
refactor!: Change ResourceSet.Contains() to ResourceSet.PermissionRequired()
refactor: Refactor to use new types from accesstypes package
=> refactor!: Change ResourceSet.Fields() to ResourceSet.FieldPermissions()

resourcestore/resourcestore.go
Co-authored-by: jwatson-ccc <jwatson-ccc@users.noreply.github.com>
=> feat: Added `Store.List()` and `Store.Scope()` methods

accesstypes/.golangci.yml, accesstypes/permission.go, accesstypes/resource.go
refactor: New Tag type and changed dependent types (#69)
refactor!: Changed method ResourceWithField() to ResourceWithTag() (#69)
=> refactor: New Tag type and changed dependent types

accesstypes/types.go
refactor!: Refactor UserPermissionCollection type (#87)
refactor!: Remove unused methods from UserPermissionCollection and RolePermissionCollection (#87)
=> refactor!: Refactor UserPermissionCollection type

ccc.go, cccutils.go, duration.go, duration_test.go, utils.go, uuid.go
feature: Implement `NullDuration` type (#104)
feature: Add `NewDuration()` and `NewDurationFromString()` constructors (#104)
=> feature: Implement NullDuration type

resourcestore/generate_typescript.go, resourcestore/resourcestore.go, resourcestore/testdata/Generate_Typescript/permissions.ts
Using modified target template from: https://github.com/AscendiumApps/ga-lite-app/blob/feature/dynamic-resource-fields/gui/src/app/core/service/resources.ts
=> refactor: update typescript generation template 

resource/generation/client.go, resource/generation/client_test.go, resource/generation/extract.go, resource/generation/handler.go, resource/generation/options.go, resource/generation/router.go, resource/generation/spanner.go, resource/generation/templates.go, resource/generation/types.go, resource/generation/typescript.go
- Replaces ast parsing with packing type checking using `types` package
- Better typing on parsed resources
- Better error messaging
- Separate parsing functions are moved into one method `extractResourceTypes`
- Updated templates for readability
=> feature: consolidate-parsing

resource/generation/client.go, resource/generation/client_test.go, resource/generation/handler.go, resource/generation/options.go, resource/generation/resource.go, resource/generation/templates.go
- copy & paste imports into the handlergen template
- fix a missed bug with client_test.go missing a parameter
=> fix: Bake imports into handler template

resource/generation/extract_test.go, resource/generation/router.go, resource/generation/templates.go, resource/generation/testdata/resources/res1.go, resource/generation/types.go
Enables manually specifying indexed columns on virtual resources (views)
=> feature: parse index tags

resource/querybuilder.go, resource/querybuilder_test.go, resource/queryset.go
first implementation of query builder
=> feature: query builder

resource/generation/templates.go, resource/generation/types.go
Resource Generator now generates `QueryClause` wrappers for all resources
=> feature: generate query clause

resource/generation/templates.go, resource/generation/types.go
=> feat: Support singular primary keys with names other than 'Id'

resource/generation/templates.go, resource/generation/types.go
=> fix: Check that the primary key is a generated UUID (vs just a UUID)

resource/dml.go, resource/keyset.go, resource/patchset.go, resource/queryset.go
fix: Fix not found error condition for filters and where clauses (#284)
fix: Ensure old values for inserts are set to nil in data change tracking (#284)
=> fix: Fix not found error condition for filters and where clauses

resource/collection.go, resource/generation/client.go, resource/generation/extract.go, resource/generation/options.go, resource/generation/types.go
=> fix: Exclude resources with no handlers from typescript resource generation

resource/generation/templates.go, resource/generation/types.go, resource/patchset.go, resource/types.go
=> feature: Implement default update function support

resource/filter.go
Adds boolean kind filters to query params.
=> feat: Added support for filtering on boolean columns

.github/workflows/security-scan.yml, go.mod
=> upgrade: Update Go version to 1.24.4 to address GO-2025-3750

resource/operations.go, resource/operations_test.go
This is needed when we consolidate multiple resources into a single PATCH handler. We must first decode the prefix of the path to know which resource we are decoding. Once we know which resource we are working with, we then know the full pattern to match the path.
=> feature: Add support for prefix matching when decoding operations

resource/generation/templates.go, resource/generation/types.go, resource/operations.go
fix: Fix bug when creating a resource via consolidated handler (#423)
fix: Fix bug in consolidated patch handler template (#423)
=> fix: Fix bug when creating a resource via consolidated handler

pkg/pkg.go
cleanup: Fix linter complaints (#448)
refactor!: Changed type PkgInfo to Information to remove stutter (#448)
=> cleanup: Fix linter complaints
